addr: "127.0.0.1:9379"

etcd:
  addrs:
    - "127.0.0.1:2379"
  username:
  password:
  tls:
    enable: false
    cert_file:
    key_file:
    ca_file:

controller:
  failover:
    gc_interval_seconds: 3600
    ping_interval_seconds: 5
    min_alive_size: 10
    max_failure_ratio: 0.6
